[2022-04-25 15:57:03,661] {processor.py:163} INFO - Started process (PID=60) to work on /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 15:57:03,689] {processor.py:642} INFO - Processing file /opt/airflow/dags/__pycache__/dag1.py for tasks to queue
[2022-04-25 15:57:03,701] {logging_mixin.py:109} INFO - [2022-04-25 15:57:03,701] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 15:57:03,753] {logging_mixin.py:109} INFO - [2022-04-25 15:57:03,752] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/__pycache__/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/dag1.py", line 9
    )
    ^
SyntaxError: invalid syntax
[2022-04-25 15:57:03,763] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 15:57:03,909] {processor.py:171} INFO - Processing /opt/airflow/dags/__pycache__/dag1.py took 0.255 seconds
[2022-04-25 15:57:34,802] {processor.py:163} INFO - Started process (PID=83) to work on /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 15:57:34,852] {processor.py:642} INFO - Processing file /opt/airflow/dags/__pycache__/dag1.py for tasks to queue
[2022-04-25 15:57:34,900] {logging_mixin.py:109} INFO - [2022-04-25 15:57:34,900] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 15:57:46,281] {logging_mixin.py:109} INFO - [2022-04-25 15:57:40,922] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/__pycache__/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/dag1.py", line 9
    )
    ^
SyntaxError: invalid syntax
[2022-04-25 15:57:46,879] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 15:57:48,512] {processor.py:171} INFO - Processing /opt/airflow/dags/__pycache__/dag1.py took 13.831 seconds
[2022-04-25 15:58:19,591] {processor.py:163} INFO - Started process (PID=103) to work on /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 15:58:19,756] {processor.py:642} INFO - Processing file /opt/airflow/dags/__pycache__/dag1.py for tasks to queue
[2022-04-25 15:58:20,026] {logging_mixin.py:109} INFO - [2022-04-25 15:58:19,774] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 15:58:20,461] {logging_mixin.py:109} INFO - [2022-04-25 15:58:20,349] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/__pycache__/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/dag1.py", line 9
    )
    ^
SyntaxError: invalid syntax
[2022-04-25 15:58:20,499] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 15:58:23,330] {processor.py:171} INFO - Processing /opt/airflow/dags/__pycache__/dag1.py took 3.989 seconds
[2022-04-25 15:58:54,667] {processor.py:163} INFO - Started process (PID=122) to work on /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 15:58:54,699] {processor.py:642} INFO - Processing file /opt/airflow/dags/__pycache__/dag1.py for tasks to queue
[2022-04-25 15:58:54,711] {logging_mixin.py:109} INFO - [2022-04-25 15:58:54,705] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 15:58:54,792] {logging_mixin.py:109} INFO - [2022-04-25 15:58:54,778] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/__pycache__/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/dag1.py", line 9
    )
    ^
SyntaxError: invalid syntax
[2022-04-25 15:58:54,803] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 15:58:56,111] {processor.py:171} INFO - Processing /opt/airflow/dags/__pycache__/dag1.py took 1.491 seconds
[2022-04-25 15:59:26,637] {processor.py:163} INFO - Started process (PID=135) to work on /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 15:59:26,644] {processor.py:642} INFO - Processing file /opt/airflow/dags/__pycache__/dag1.py for tasks to queue
[2022-04-25 15:59:26,647] {logging_mixin.py:109} INFO - [2022-04-25 15:59:26,646] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 15:59:26,662] {logging_mixin.py:109} INFO - [2022-04-25 15:59:26,660] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/__pycache__/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/dag1.py", line 9
    )
    ^
SyntaxError: invalid syntax
[2022-04-25 15:59:26,664] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 15:59:26,723] {processor.py:171} INFO - Processing /opt/airflow/dags/__pycache__/dag1.py took 0.100 seconds
[2022-04-25 15:59:59,421] {processor.py:163} INFO - Started process (PID=156) to work on /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 15:59:59,456] {processor.py:642} INFO - Processing file /opt/airflow/dags/__pycache__/dag1.py for tasks to queue
[2022-04-25 15:59:59,479] {logging_mixin.py:109} INFO - [2022-04-25 15:59:59,479] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 15:59:59,571] {logging_mixin.py:109} INFO - [2022-04-25 15:59:59,548] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/__pycache__/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/dag1.py", line 9
    )
    ^
SyntaxError: invalid syntax
[2022-04-25 15:59:59,583] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 15:59:59,843] {processor.py:171} INFO - Processing /opt/airflow/dags/__pycache__/dag1.py took 0.516 seconds
[2022-04-25 16:02:39,389] {processor.py:163} INFO - Started process (PID=66) to work on /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:02:39,415] {processor.py:642} INFO - Processing file /opt/airflow/dags/__pycache__/dag1.py for tasks to queue
[2022-04-25 16:02:39,439] {logging_mixin.py:109} INFO - [2022-04-25 16:02:39,439] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:02:39,501] {logging_mixin.py:109} INFO - [2022-04-25 16:02:39,481] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/__pycache__/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/dag1.py", line 9
    )
    ^
SyntaxError: invalid syntax
[2022-04-25 16:02:39,503] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:02:39,676] {processor.py:171} INFO - Processing /opt/airflow/dags/__pycache__/dag1.py took 0.377 seconds
[2022-04-25 16:03:10,003] {processor.py:163} INFO - Started process (PID=79) to work on /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:03:10,021] {processor.py:642} INFO - Processing file /opt/airflow/dags/__pycache__/dag1.py for tasks to queue
[2022-04-25 16:03:10,023] {logging_mixin.py:109} INFO - [2022-04-25 16:03:10,023] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:03:10,052] {logging_mixin.py:109} INFO - [2022-04-25 16:03:10,048] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/__pycache__/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/dag1.py", line 9
    )
    ^
SyntaxError: invalid syntax
[2022-04-25 16:03:10,055] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:03:10,249] {processor.py:171} INFO - Processing /opt/airflow/dags/__pycache__/dag1.py took 0.287 seconds
[2022-04-25 16:03:42,115] {processor.py:163} INFO - Started process (PID=99) to work on /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:03:42,161] {processor.py:642} INFO - Processing file /opt/airflow/dags/__pycache__/dag1.py for tasks to queue
[2022-04-25 16:03:42,216] {logging_mixin.py:109} INFO - [2022-04-25 16:03:42,206] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:03:42,307] {logging_mixin.py:109} INFO - [2022-04-25 16:03:42,292] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/__pycache__/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/dag1.py", line 9
    )
    ^
SyntaxError: invalid syntax
[2022-04-25 16:03:42,326] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:03:42,768] {processor.py:171} INFO - Processing /opt/airflow/dags/__pycache__/dag1.py took 0.766 seconds
[2022-04-25 16:04:13,764] {processor.py:163} INFO - Started process (PID=110) to work on /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:04:13,771] {processor.py:642} INFO - Processing file /opt/airflow/dags/__pycache__/dag1.py for tasks to queue
[2022-04-25 16:04:13,776] {logging_mixin.py:109} INFO - [2022-04-25 16:04:13,775] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:04:13,816] {logging_mixin.py:109} INFO - [2022-04-25 16:04:13,804] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/__pycache__/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/dag1.py", line 9
    )
    ^
SyntaxError: invalid syntax
[2022-04-25 16:04:13,819] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:04:13,932] {processor.py:171} INFO - Processing /opt/airflow/dags/__pycache__/dag1.py took 0.180 seconds
[2022-04-25 16:04:44,358] {processor.py:163} INFO - Started process (PID=132) to work on /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:04:44,370] {processor.py:642} INFO - Processing file /opt/airflow/dags/__pycache__/dag1.py for tasks to queue
[2022-04-25 16:04:44,402] {logging_mixin.py:109} INFO - [2022-04-25 16:04:44,401] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:04:44,452] {logging_mixin.py:109} INFO - [2022-04-25 16:04:44,449] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/__pycache__/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/dag1.py", line 9
    )
    ^
SyntaxError: invalid syntax
[2022-04-25 16:04:44,467] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:04:44,628] {processor.py:171} INFO - Processing /opt/airflow/dags/__pycache__/dag1.py took 0.293 seconds
[2022-04-25 16:05:19,187] {processor.py:163} INFO - Started process (PID=150) to work on /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:05:19,265] {processor.py:642} INFO - Processing file /opt/airflow/dags/__pycache__/dag1.py for tasks to queue
[2022-04-25 16:05:19,281] {logging_mixin.py:109} INFO - [2022-04-25 16:05:19,281] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:05:19,379] {logging_mixin.py:109} INFO - [2022-04-25 16:05:19,377] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/__pycache__/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/dag1.py", line 9
    )
    ^
SyntaxError: invalid syntax
[2022-04-25 16:05:19,416] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:05:20,033] {processor.py:171} INFO - Processing /opt/airflow/dags/__pycache__/dag1.py took 1.093 seconds
[2022-04-25 16:05:50,837] {processor.py:163} INFO - Started process (PID=163) to work on /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:05:50,861] {processor.py:642} INFO - Processing file /opt/airflow/dags/__pycache__/dag1.py for tasks to queue
[2022-04-25 16:05:50,893] {logging_mixin.py:109} INFO - [2022-04-25 16:05:50,893] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:05:50,948] {logging_mixin.py:109} INFO - [2022-04-25 16:05:50,930] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/__pycache__/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/dag1.py", line 9
    )
    ^
SyntaxError: invalid syntax
[2022-04-25 16:05:51,058] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:05:51,281] {processor.py:171} INFO - Processing /opt/airflow/dags/__pycache__/dag1.py took 0.467 seconds
[2022-04-25 16:06:21,802] {processor.py:163} INFO - Started process (PID=185) to work on /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:06:21,806] {processor.py:642} INFO - Processing file /opt/airflow/dags/__pycache__/dag1.py for tasks to queue
[2022-04-25 16:06:21,808] {logging_mixin.py:109} INFO - [2022-04-25 16:06:21,808] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:06:21,843] {logging_mixin.py:109} INFO - [2022-04-25 16:06:21,836] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/__pycache__/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/dag1.py", line 9
    )
    ^
SyntaxError: invalid syntax
[2022-04-25 16:06:21,848] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:06:21,943] {processor.py:171} INFO - Processing /opt/airflow/dags/__pycache__/dag1.py took 0.154 seconds
[2022-04-25 16:06:52,317] {processor.py:163} INFO - Started process (PID=208) to work on /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:06:52,329] {processor.py:642} INFO - Processing file /opt/airflow/dags/__pycache__/dag1.py for tasks to queue
[2022-04-25 16:06:52,332] {logging_mixin.py:109} INFO - [2022-04-25 16:06:52,331] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:06:52,357] {logging_mixin.py:109} INFO - [2022-04-25 16:06:52,356] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/__pycache__/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/dag1.py", line 9
    )
    ^
SyntaxError: invalid syntax
[2022-04-25 16:06:52,363] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:06:52,446] {processor.py:171} INFO - Processing /opt/airflow/dags/__pycache__/dag1.py took 0.134 seconds
[2022-04-25 16:07:22,718] {processor.py:163} INFO - Started process (PID=230) to work on /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:07:22,721] {processor.py:642} INFO - Processing file /opt/airflow/dags/__pycache__/dag1.py for tasks to queue
[2022-04-25 16:07:22,723] {logging_mixin.py:109} INFO - [2022-04-25 16:07:22,722] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:07:22,764] {logging_mixin.py:109} INFO - [2022-04-25 16:07:22,762] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/__pycache__/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/dag1.py", line 9
    )
    ^
SyntaxError: invalid syntax
[2022-04-25 16:07:22,767] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:07:22,809] {processor.py:171} INFO - Processing /opt/airflow/dags/__pycache__/dag1.py took 0.095 seconds
[2022-04-25 16:07:53,158] {processor.py:163} INFO - Started process (PID=264) to work on /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:07:53,162] {processor.py:642} INFO - Processing file /opt/airflow/dags/__pycache__/dag1.py for tasks to queue
[2022-04-25 16:07:53,167] {logging_mixin.py:109} INFO - [2022-04-25 16:07:53,167] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:07:53,196] {logging_mixin.py:109} INFO - [2022-04-25 16:07:53,195] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/__pycache__/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/dag1.py", line 9
    )
    ^
SyntaxError: invalid syntax
[2022-04-25 16:07:53,200] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:07:53,272] {processor.py:171} INFO - Processing /opt/airflow/dags/__pycache__/dag1.py took 0.122 seconds
[2022-04-25 16:08:23,499] {processor.py:163} INFO - Started process (PID=285) to work on /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:08:23,506] {processor.py:642} INFO - Processing file /opt/airflow/dags/__pycache__/dag1.py for tasks to queue
[2022-04-25 16:08:23,510] {logging_mixin.py:109} INFO - [2022-04-25 16:08:23,509] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:08:23,526] {logging_mixin.py:109} INFO - [2022-04-25 16:08:23,522] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/__pycache__/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/dag1.py", line 9
    )
    ^
SyntaxError: invalid syntax
[2022-04-25 16:08:23,530] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:08:23,627] {processor.py:171} INFO - Processing /opt/airflow/dags/__pycache__/dag1.py took 0.148 seconds
[2022-04-25 16:08:53,765] {processor.py:163} INFO - Started process (PID=308) to work on /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:08:53,769] {processor.py:642} INFO - Processing file /opt/airflow/dags/__pycache__/dag1.py for tasks to queue
[2022-04-25 16:08:53,771] {logging_mixin.py:109} INFO - [2022-04-25 16:08:53,771] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:08:53,789] {logging_mixin.py:109} INFO - [2022-04-25 16:08:53,783] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/__pycache__/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/dag1.py", line 9
    )
    ^
SyntaxError: invalid syntax
[2022-04-25 16:08:53,790] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:08:53,822] {processor.py:171} INFO - Processing /opt/airflow/dags/__pycache__/dag1.py took 0.063 seconds
[2022-04-25 16:09:24,758] {processor.py:163} INFO - Started process (PID=340) to work on /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:09:24,765] {processor.py:642} INFO - Processing file /opt/airflow/dags/__pycache__/dag1.py for tasks to queue
[2022-04-25 16:09:24,770] {logging_mixin.py:109} INFO - [2022-04-25 16:09:24,770] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:09:24,784] {logging_mixin.py:109} INFO - [2022-04-25 16:09:24,781] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/__pycache__/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/dag1.py", line 9
    )
    ^
SyntaxError: invalid syntax
[2022-04-25 16:09:24,786] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/dag1.py
[2022-04-25 16:09:24,838] {processor.py:171} INFO - Processing /opt/airflow/dags/__pycache__/dag1.py took 0.084 seconds
