[2022-04-28 10:44:36,027] {processor.py:163} INFO - Started process (PID=51) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:44:36,035] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 10:44:36,043] {logging_mixin.py:109} INFO - [2022-04-28 10:44:36,043] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:44:36,067] {logging_mixin.py:109} INFO - [2022-04-28 10:44:36,063] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6
    from ~/py_code import extract
         ^
SyntaxError: invalid syntax
[2022-04-28 10:44:36,073] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:44:36,134] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.112 seconds
[2022-04-28 10:45:07,256] {processor.py:163} INFO - Started process (PID=70) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:45:07,324] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 10:45:07,372] {logging_mixin.py:109} INFO - [2022-04-28 10:45:07,372] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:45:07,495] {logging_mixin.py:109} INFO - [2022-04-28 10:45:07,426] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6
    from ~/py_code import extract
         ^
SyntaxError: invalid syntax
[2022-04-28 10:45:07,523] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:45:07,949] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 1.095 seconds
[2022-04-28 10:45:40,946] {processor.py:163} INFO - Started process (PID=87) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:45:41,023] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 10:45:41,065] {logging_mixin.py:109} INFO - [2022-04-28 10:45:41,064] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:45:41,245] {logging_mixin.py:109} INFO - [2022-04-28 10:45:41,194] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6
    from ~/py_code import extract
         ^
SyntaxError: invalid syntax
[2022-04-28 10:45:41,257] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:45:42,124] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 2.297 seconds
[2022-04-28 10:46:12,891] {processor.py:163} INFO - Started process (PID=99) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:46:12,911] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 10:46:12,920] {logging_mixin.py:109} INFO - [2022-04-28 10:46:12,920] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:46:12,974] {logging_mixin.py:109} INFO - [2022-04-28 10:46:12,961] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6
    from ~/py_code import extract
         ^
SyntaxError: invalid syntax
[2022-04-28 10:46:12,992] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:46:13,270] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.418 seconds
[2022-04-28 10:46:44,598] {processor.py:163} INFO - Started process (PID=118) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:46:44,607] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 10:46:44,613] {logging_mixin.py:109} INFO - [2022-04-28 10:46:44,612] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:46:44,820] {logging_mixin.py:109} INFO - [2022-04-28 10:46:44,817] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6
    from ~/py_code import extract
         ^
SyntaxError: invalid syntax
[2022-04-28 10:46:44,867] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:46:45,173] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.599 seconds
[2022-04-28 10:47:15,240] {processor.py:163} INFO - Started process (PID=140) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:47:15,245] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 10:47:15,248] {logging_mixin.py:109} INFO - [2022-04-28 10:47:15,247] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:47:15,266] {logging_mixin.py:109} INFO - [2022-04-28 10:47:15,263] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6
    from ~/py_code import extract
         ^
SyntaxError: invalid syntax
[2022-04-28 10:47:15,272] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:47:15,312] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.078 seconds
[2022-04-28 10:47:45,538] {processor.py:163} INFO - Started process (PID=161) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:47:45,541] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 10:47:45,545] {logging_mixin.py:109} INFO - [2022-04-28 10:47:45,544] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:47:45,568] {logging_mixin.py:109} INFO - [2022-04-28 10:47:45,566] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6
    from ~/py_code import extract
         ^
SyntaxError: invalid syntax
[2022-04-28 10:47:45,571] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:47:45,627] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.096 seconds
[2022-04-28 10:48:15,857] {processor.py:163} INFO - Started process (PID=182) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:48:15,864] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 10:48:15,865] {logging_mixin.py:109} INFO - [2022-04-28 10:48:15,865] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:48:15,881] {logging_mixin.py:109} INFO - [2022-04-28 10:48:15,879] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6
    from ~/py_code import extract
         ^
SyntaxError: invalid syntax
[2022-04-28 10:48:15,884] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:48:15,935] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.087 seconds
[2022-04-28 10:48:22,913] {processor.py:163} INFO - Started process (PID=192) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:48:22,916] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 10:48:22,918] {logging_mixin.py:109} INFO - [2022-04-28 10:48:22,917] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:48:23,603] {logging_mixin.py:109} INFO - [2022-04-28 10:48:23,599] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from py_code import extract
ModuleNotFoundError: No module named 'py_code'
[2022-04-28 10:48:23,626] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:48:23,695] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.786 seconds
[2022-04-28 10:48:53,185] {processor.py:163} INFO - Started process (PID=212) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:48:53,194] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 10:48:53,196] {logging_mixin.py:109} INFO - [2022-04-28 10:48:53,196] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:48:53,252] {logging_mixin.py:109} INFO - [2022-04-28 10:48:53,244] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from airflow.py_code import extract
ModuleNotFoundError: No module named 'airflow.py_code'
[2022-04-28 10:48:53,254] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:48:53,290] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.112 seconds
[2022-04-28 10:49:23,559] {processor.py:163} INFO - Started process (PID=233) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:49:23,566] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 10:49:23,568] {logging_mixin.py:109} INFO - [2022-04-28 10:49:23,568] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:49:23,604] {logging_mixin.py:109} INFO - [2022-04-28 10:49:23,597] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from airflow.py_code import extract
ModuleNotFoundError: No module named 'airflow.py_code'
[2022-04-28 10:49:23,607] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:49:23,654] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.099 seconds
[2022-04-28 10:49:54,099] {processor.py:163} INFO - Started process (PID=255) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:49:54,102] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 10:49:54,104] {logging_mixin.py:109} INFO - [2022-04-28 10:49:54,104] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:49:54,131] {logging_mixin.py:109} INFO - [2022-04-28 10:49:54,126] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from airflow.py_code import extract
ModuleNotFoundError: No module named 'airflow.py_code'
[2022-04-28 10:49:54,132] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:49:54,168] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.073 seconds
[2022-04-28 10:49:59,141] {processor.py:163} INFO - Started process (PID=256) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:49:59,151] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 10:49:59,156] {logging_mixin.py:109} INFO - [2022-04-28 10:49:59,154] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:49:59,263] {logging_mixin.py:109} INFO - [2022-04-28 10:49:59,256] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 10:49:59,267] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:49:59,311] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.176 seconds
[2022-04-28 10:50:29,419] {processor.py:163} INFO - Started process (PID=277) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:50:29,425] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 10:50:29,428] {logging_mixin.py:109} INFO - [2022-04-28 10:50:29,427] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:50:29,456] {logging_mixin.py:109} INFO - [2022-04-28 10:50:29,453] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 10:50:29,459] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:50:29,505] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.092 seconds
[2022-04-28 10:50:59,597] {processor.py:163} INFO - Started process (PID=297) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:50:59,603] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 10:50:59,607] {logging_mixin.py:109} INFO - [2022-04-28 10:50:59,606] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:50:59,650] {logging_mixin.py:109} INFO - [2022-04-28 10:50:59,646] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 10:50:59,653] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:50:59,704] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.115 seconds
[2022-04-28 10:51:29,824] {processor.py:163} INFO - Started process (PID=316) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:51:29,827] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 10:51:29,829] {logging_mixin.py:109} INFO - [2022-04-28 10:51:29,829] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:51:29,851] {logging_mixin.py:109} INFO - [2022-04-28 10:51:29,847] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 10:51:29,853] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:51:29,894] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.078 seconds
[2022-04-28 10:51:59,957] {processor.py:163} INFO - Started process (PID=345) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:51:59,977] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 10:51:59,979] {logging_mixin.py:109} INFO - [2022-04-28 10:51:59,979] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:52:00,001] {logging_mixin.py:109} INFO - [2022-04-28 10:51:59,998] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 10:52:00,006] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:52:00,045] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.092 seconds
[2022-04-28 10:52:30,094] {processor.py:163} INFO - Started process (PID=369) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:52:30,100] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 10:52:30,103] {logging_mixin.py:109} INFO - [2022-04-28 10:52:30,103] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:52:30,127] {logging_mixin.py:109} INFO - [2022-04-28 10:52:30,124] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 10:52:30,129] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:52:30,167] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.081 seconds
[2022-04-28 10:53:00,296] {processor.py:163} INFO - Started process (PID=402) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:53:00,304] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 10:53:00,316] {logging_mixin.py:109} INFO - [2022-04-28 10:53:00,316] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:53:00,370] {logging_mixin.py:109} INFO - [2022-04-28 10:53:00,368] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 10:53:00,376] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:53:00,415] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.131 seconds
[2022-04-28 10:53:30,533] {processor.py:163} INFO - Started process (PID=425) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:53:30,538] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 10:53:30,544] {logging_mixin.py:109} INFO - [2022-04-28 10:53:30,543] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:53:30,590] {logging_mixin.py:109} INFO - [2022-04-28 10:53:30,585] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 10:53:30,593] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:53:30,633] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.106 seconds
[2022-04-28 10:54:00,741] {processor.py:163} INFO - Started process (PID=447) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:54:00,744] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 10:54:00,745] {logging_mixin.py:109} INFO - [2022-04-28 10:54:00,745] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:54:00,768] {logging_mixin.py:109} INFO - [2022-04-28 10:54:00,766] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 10:54:00,769] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:54:00,803] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.067 seconds
[2022-04-28 10:54:30,955] {processor.py:163} INFO - Started process (PID=468) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:54:30,958] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 10:54:30,961] {logging_mixin.py:109} INFO - [2022-04-28 10:54:30,960] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:54:30,989] {logging_mixin.py:109} INFO - [2022-04-28 10:54:30,985] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 10:54:30,992] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:54:31,038] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.089 seconds
[2022-04-28 10:55:01,204] {processor.py:163} INFO - Started process (PID=499) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:55:01,220] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 10:55:01,223] {logging_mixin.py:109} INFO - [2022-04-28 10:55:01,223] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:55:01,256] {logging_mixin.py:109} INFO - [2022-04-28 10:55:01,251] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 10:55:01,258] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:55:01,295] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.094 seconds
[2022-04-28 10:55:31,356] {processor.py:163} INFO - Started process (PID=521) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:55:31,361] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 10:55:31,363] {logging_mixin.py:109} INFO - [2022-04-28 10:55:31,363] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:55:31,385] {logging_mixin.py:109} INFO - [2022-04-28 10:55:31,382] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 10:55:31,387] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:55:31,418] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.069 seconds
[2022-04-28 10:56:01,538] {processor.py:163} INFO - Started process (PID=544) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:56:01,542] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 10:56:01,545] {logging_mixin.py:109} INFO - [2022-04-28 10:56:01,545] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:56:01,584] {logging_mixin.py:109} INFO - [2022-04-28 10:56:01,577] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 10:56:01,591] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:56:01,640] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.108 seconds
[2022-04-28 10:56:31,707] {processor.py:163} INFO - Started process (PID=576) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:56:31,720] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 10:56:31,723] {logging_mixin.py:109} INFO - [2022-04-28 10:56:31,723] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:56:31,760] {logging_mixin.py:109} INFO - [2022-04-28 10:56:31,756] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 10:56:31,762] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:56:31,813] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.118 seconds
[2022-04-28 10:57:01,932] {processor.py:163} INFO - Started process (PID=598) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:57:01,934] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 10:57:01,936] {logging_mixin.py:109} INFO - [2022-04-28 10:57:01,936] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:57:01,957] {logging_mixin.py:109} INFO - [2022-04-28 10:57:01,954] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 10:57:01,958] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:57:01,991] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.065 seconds
[2022-04-28 10:57:32,063] {processor.py:163} INFO - Started process (PID=618) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:57:32,087] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 10:57:32,091] {logging_mixin.py:109} INFO - [2022-04-28 10:57:32,091] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:57:32,124] {logging_mixin.py:109} INFO - [2022-04-28 10:57:32,122] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 10:57:32,127] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 10:57:32,163] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.109 seconds
[2022-04-28 11:01:02,652] {processor.py:163} INFO - Started process (PID=640) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 11:01:02,661] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 11:01:02,794] {logging_mixin.py:109} INFO - [2022-04-28 11:01:02,794] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 11:01:03,306] {logging_mixin.py:109} INFO - [2022-04-28 11:01:03,279] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 11:01:03,312] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 11:01:03,650] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 1.039 seconds
[2022-04-28 11:01:34,565] {processor.py:163} INFO - Started process (PID=661) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 11:01:34,573] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 11:01:34,576] {logging_mixin.py:109} INFO - [2022-04-28 11:01:34,576] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 11:01:34,608] {logging_mixin.py:109} INFO - [2022-04-28 11:01:34,605] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 11:01:34,610] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 11:01:34,654] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.097 seconds
[2022-04-28 14:28:52,939] {processor.py:163} INFO - Started process (PID=60) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 14:28:52,943] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 14:28:52,961] {logging_mixin.py:109} INFO - [2022-04-28 14:28:52,961] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 14:28:53,126] {logging_mixin.py:109} INFO - [2022-04-28 14:28:53,115] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 14:28:53,130] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 14:28:53,232] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.323 seconds
[2022-04-28 14:29:23,985] {processor.py:163} INFO - Started process (PID=79) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 14:29:24,028] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 14:29:24,050] {logging_mixin.py:109} INFO - [2022-04-28 14:29:24,049] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 14:29:24,523] {logging_mixin.py:109} INFO - [2022-04-28 14:29:24,510] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 14:29:24,528] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 14:29:24,781] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.885 seconds
[2022-04-28 14:29:55,563] {processor.py:163} INFO - Started process (PID=89) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 14:29:55,585] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 14:29:55,590] {logging_mixin.py:109} INFO - [2022-04-28 14:29:55,589] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 14:29:55,684] {logging_mixin.py:109} INFO - [2022-04-28 14:29:55,678] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 14:29:55,688] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 14:29:55,756] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.210 seconds
[2022-04-28 14:30:25,853] {processor.py:163} INFO - Started process (PID=118) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 14:30:25,857] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 14:30:25,859] {logging_mixin.py:109} INFO - [2022-04-28 14:30:25,859] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 14:30:25,911] {logging_mixin.py:109} INFO - [2022-04-28 14:30:25,906] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 14:30:25,915] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 14:30:25,974] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.125 seconds
[2022-04-28 14:30:56,105] {processor.py:163} INFO - Started process (PID=138) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 14:30:56,108] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 14:30:56,113] {logging_mixin.py:109} INFO - [2022-04-28 14:30:56,113] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 14:30:56,152] {logging_mixin.py:109} INFO - [2022-04-28 14:30:56,143] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 14:30:56,158] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 14:30:56,216] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.118 seconds
[2022-04-28 14:31:26,271] {processor.py:163} INFO - Started process (PID=160) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 14:31:26,274] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 14:31:26,278] {logging_mixin.py:109} INFO - [2022-04-28 14:31:26,278] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 14:31:26,319] {logging_mixin.py:109} INFO - [2022-04-28 14:31:26,313] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 14:31:26,322] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 14:31:26,362] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.100 seconds
[2022-04-28 14:31:57,294] {processor.py:163} INFO - Started process (PID=185) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 14:31:57,302] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 14:31:57,332] {logging_mixin.py:109} INFO - [2022-04-28 14:31:57,332] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 14:31:57,452] {logging_mixin.py:109} INFO - [2022-04-28 14:31:57,445] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 14:31:57,460] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 14:31:57,503] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.542 seconds
[2022-04-28 14:32:27,804] {processor.py:163} INFO - Started process (PID=208) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 14:32:27,808] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 14:32:27,810] {logging_mixin.py:109} INFO - [2022-04-28 14:32:27,810] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 14:32:27,831] {logging_mixin.py:109} INFO - [2022-04-28 14:32:27,828] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 14:32:27,833] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 14:32:27,871] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.072 seconds
[2022-04-28 14:32:57,978] {processor.py:163} INFO - Started process (PID=230) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 14:32:57,982] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 14:32:57,984] {logging_mixin.py:109} INFO - [2022-04-28 14:32:57,984] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 14:32:58,007] {logging_mixin.py:109} INFO - [2022-04-28 14:32:58,004] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 14:32:58,008] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 14:32:58,041] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.067 seconds
[2022-04-28 15:02:15,598] {processor.py:163} INFO - Started process (PID=248) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:02:15,730] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 15:02:15,745] {logging_mixin.py:109} INFO - [2022-04-28 15:02:15,745] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:02:15,889] {logging_mixin.py:109} INFO - [2022-04-28 15:02:15,866] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 15:02:15,891] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:02:16,170] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.589 seconds
[2022-04-28 15:02:47,439] {processor.py:163} INFO - Started process (PID=271) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:02:47,446] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 15:02:47,454] {logging_mixin.py:109} INFO - [2022-04-28 15:02:47,454] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:02:47,513] {logging_mixin.py:109} INFO - [2022-04-28 15:02:47,505] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 15:02:47,522] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:02:47,685] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.254 seconds
[2022-04-28 15:03:17,853] {processor.py:163} INFO - Started process (PID=293) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:03:17,864] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 15:03:17,865] {logging_mixin.py:109} INFO - [2022-04-28 15:03:17,865] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:03:17,888] {logging_mixin.py:109} INFO - [2022-04-28 15:03:17,885] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 15:03:17,890] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:03:17,924] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.075 seconds
[2022-04-28 15:03:48,032] {processor.py:163} INFO - Started process (PID=313) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:03:48,037] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 15:03:48,040] {logging_mixin.py:109} INFO - [2022-04-28 15:03:48,039] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:03:48,072] {logging_mixin.py:109} INFO - [2022-04-28 15:03:48,068] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 15:03:48,074] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:03:48,113] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.089 seconds
[2022-04-28 15:04:18,265] {processor.py:163} INFO - Started process (PID=337) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:04:18,269] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 15:04:18,272] {logging_mixin.py:109} INFO - [2022-04-28 15:04:18,272] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:04:18,312] {logging_mixin.py:109} INFO - [2022-04-28 15:04:18,309] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 15:04:18,320] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:04:18,384] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.125 seconds
[2022-04-28 15:04:48,486] {processor.py:163} INFO - Started process (PID=356) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:04:48,547] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 15:04:48,560] {logging_mixin.py:109} INFO - [2022-04-28 15:04:48,559] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:04:48,639] {logging_mixin.py:109} INFO - [2022-04-28 15:04:48,630] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 15:04:48,644] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:04:48,697] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.219 seconds
[2022-04-28 15:05:19,003] {processor.py:163} INFO - Started process (PID=384) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:05:19,020] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 15:05:19,028] {logging_mixin.py:109} INFO - [2022-04-28 15:05:19,028] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:05:19,193] {logging_mixin.py:109} INFO - [2022-04-28 15:05:19,179] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/starwar_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/starwar_dag.py", line 6, in <module>
    from opt.airflow.py_code import extract
ModuleNotFoundError: No module named 'opt'
[2022-04-28 15:05:19,201] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:05:19,822] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.899 seconds
[2022-04-28 15:05:46,162] {processor.py:163} INFO - Started process (PID=396) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:05:46,172] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 15:05:46,177] {logging_mixin.py:109} INFO - [2022-04-28 15:05:46,177] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:05:46,873] {processor.py:652} INFO - DAG(s) dict_keys(['starwarapi']) retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:06:45,843] {processor.py:163} INFO - Started process (PID=424) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:06:46,025] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 15:06:46,065] {logging_mixin.py:109} INFO - [2022-04-28 15:06:46,061] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:06:48,780] {processor.py:652} INFO - DAG(s) dict_keys(['starwarapi']) retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:07:39,691] {processor.py:163} INFO - Started process (PID=453) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:07:39,695] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 15:07:39,697] {logging_mixin.py:109} INFO - [2022-04-28 15:07:39,697] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:07:39,924] {processor.py:652} INFO - DAG(s) dict_keys(['starwarapi']) retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:08:31,201] {processor.py:163} INFO - Started process (PID=478) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:08:31,212] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 15:08:31,233] {logging_mixin.py:109} INFO - [2022-04-28 15:08:31,232] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:08:31,451] {processor.py:652} INFO - DAG(s) dict_keys(['starwarapi']) retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:08:42,773] {logging_mixin.py:109} INFO - [2022-04-28 15:08:42,771] {manager.py:496} INFO - Created Permission View: can read on DAG:starwarapi
[2022-04-28 15:08:42,854] {logging_mixin.py:109} INFO - [2022-04-28 15:08:42,853] {manager.py:496} INFO - Created Permission View: can edit on DAG:starwarapi
[2022-04-28 15:08:42,862] {logging_mixin.py:109} INFO - [2022-04-28 15:08:42,860] {dag.py:2398} INFO - Sync 1 DAGs
[2022-04-28 15:08:43,507] {logging_mixin.py:109} INFO - [2022-04-28 15:08:43,504] {dag.py:2417} INFO - Creating ORM DAG for starwarapi
[2022-04-28 15:08:43,673] {logging_mixin.py:109} INFO - [2022-04-28 15:08:43,673] {dag.py:2937} INFO - Setting next_dagrun for starwarapi to 2022-04-28T15:07:43.672614+00:00
[2022-04-28 15:08:43,763] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 12.475 seconds
[2022-04-28 15:09:14,267] {processor.py:163} INFO - Started process (PID=510) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:09:14,274] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 15:09:14,290] {logging_mixin.py:109} INFO - [2022-04-28 15:09:14,289] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:09:14,576] {processor.py:652} INFO - DAG(s) dict_keys(['starwarapi']) retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:09:14,698] {logging_mixin.py:109} INFO - [2022-04-28 15:09:14,698] {dag.py:2398} INFO - Sync 1 DAGs
[2022-04-28 15:09:14,765] {logging_mixin.py:109} INFO - [2022-04-28 15:09:14,765] {dag.py:2937} INFO - Setting next_dagrun for starwarapi to 2022-04-28T15:08:14.764895+00:00
[2022-04-28 15:09:14,830] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.594 seconds
[2022-04-28 15:09:46,022] {processor.py:163} INFO - Started process (PID=523) to work on /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:09:46,027] {processor.py:642} INFO - Processing file /opt/airflow/dags/starwar_dag.py for tasks to queue
[2022-04-28 15:09:46,030] {logging_mixin.py:109} INFO - [2022-04-28 15:09:46,030] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:09:46,155] {processor.py:652} INFO - DAG(s) dict_keys(['starwarapi']) retrieved from /opt/airflow/dags/starwar_dag.py
[2022-04-28 15:09:46,246] {logging_mixin.py:109} INFO - [2022-04-28 15:09:46,246] {dag.py:2398} INFO - Sync 1 DAGs
[2022-04-28 15:09:46,319] {logging_mixin.py:109} INFO - [2022-04-28 15:09:46,319] {dag.py:2937} INFO - Setting next_dagrun for starwarapi to 2022-04-28T15:08:46.319176+00:00
[2022-04-28 15:09:46,351] {processor.py:171} INFO - Processing /opt/airflow/dags/starwar_dag.py took 0.355 seconds
